#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#Make sure the .ssh and files have the correct access rights
if [ -n "$public_key" ]; then
    chown -R $app:$app "$install_dir/.ssh"
    chmod 700 "$install_dir/.ssh"
    chmod 600 "$install_dir/.ssh/authorized_keys"

    _install_restart_script_and_sudoers
fi

#=================================================
# REINSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Reinstalling NodeJS..."

nodejs_install

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/logrotate.d/$app"

mkdir --parents /var/log/$app

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

yunohost service add $app --description="A Cors proxy letting the browser manages cookies and redirects." --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's services..."

ynh_systemctl  --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
