#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

# Missing settings ?
if [ -z "${public_key+x}" ]; then
    public_key=""
    ynh_app_setting_set --key=public_key --value="$public_key"
fi
if [ -z "${install_chromium+x}" ]; then
    install_chromium="false"
    ynh_app_setting_set --key=install_chromium --value="$install_chromium"
fi

#=================================================
# INSTALL NODEJS
#=================================================
ynh_script_progression "Upgrading NodeJS..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
# FIXME: this is still supported but the recommendation is now to *always* re-setup the app sources wether or not the upstream sources changed
if ynh_app_upstream_version_changed; then
    ynh_script_progression "Upgrading source files..."

    # Download, check integrity, uncompress and patch the source from amd64.src
    ynh_setup_source --dest_dir="$install_dir/package" --full_replace
fi

if [ -n "$public_key" ]; then
    ynh_script_progression "Enabling ssh access for dev..."
    # enable ssh access to the files for updates
    # todo: Secure it more with https://github.com/YunoHost-Apps/ssh_chroot_dir_ynh
    mkdir --parents "$install_dir/.ssh"
    ynh_config_add --template="authorized_keys" --destination="$install_dir/.ssh/authorized_keys"

    chown -R "$app:$app" "$install_dir/.ssh"
    chmod 700 "$install_dir/.ssh"
    chmod 600 "$install_dir/.ssh/authorized_keys"

    _install_restart_script_and_sudoers
fi

#=================================================
# Install chromium
#=================================================

if [ "$install_chromium" -eq 1 ]; then
    ynh_script_progression "Upgrading Chromium..."

    # Remove old versions of chrome
    ynh_safe_rm "$install_dir/.cache/puppeteer/chrome"

    pushd "$install_dir/package"
        ynh_exec_as_app node "./node_modules/puppeteer/install.js"
    popd
fi

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

_generate_env_file

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

# Create a dedicated NGINX config
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add $app --description="A Cors proxy letting the browser manages cookies and redirects." --log="/var/log/$app/$app.log"

# Use logrotate to manage app-specific logfile(s)
ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
